SIMTYPE_AUTOTAG = 'auto'
SIMTYPE_SIMILARITY = 'tagged'
SIMTYPE_ALL = 'all'

simtypes = (
    SIMTYPE_SIMILARITY,
    SIMTYPE_AUTOTAG,
    SIMTYPE_ALL
)

DATAONTOSEARCH_ENGINE = 'dataontosearch'
GOOGLE_ENGINE = 'google'

engines = (
    DATAONTOSEARCH_ENGINE,
    GOOGLE_ENGINE,
)
